<?php

return [[	"name"	=>	"phi",
	 	"title"	=>	"Uhol náklonu modelu Segway"],
	 ["name"	=>	"actuartor_1",
	 	"title"	=>	"Akčný zásah do motorov"],
	 ["name"	=>	"velocity_L",
	 	"title"	=>	"Rýchlosť ľavého kolesa"],
	 ["name"	=>	"velocity_R",
	 	"title"	=>	"Rýchlosť pravého kolesa"],
	 ["name"	=>	"Avelocity_L",
	 	"title"	=>	"Uhlová rýchlosť ľavého kolesa"],
	 ["name"	=>	"Avelocity_R",
	 	"title"	=>	"Uhlová rýchlosť pravého kolesa"],
	 ["name"	=>	"distance_L",
	 	"title"	=>	"Prejdená vzdialenosť ľavým kolesom v cm"],
	 ["name"	=>	"distance_R",
	 	"title"	=>	"Prejdená vzdialenosť pravým kolesom v cm"],
	 ["name"	=>	"angle_L",
	 	"title"	=>	"Prejdená vzdialenosť ľavým kolesom v rad"],
	 ["name"	=>	"angle_R",
	 	"title"	=>	"Prejdená vzdialenosť pravým kolesom v rad"],
	 ["name"	=>	"servo_tazisko",
	 	"title"	=>	"Poloha serva pre zmenu ťažiska"]];

